# Generated by Django 5.1 on 2024-08-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id_carpeta', models.AutoField(primary_key=True, serialize=False)),
                ('carpeta', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carpetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
    ]
